language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - CI=false npm run build
deploy:
  provider: pages
  cleanup: true
  GITHUB_TOKEN: $github_token
  local_dir: build
  on:
    branch: dev
  target_branch: master