language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - CI=false npm run build
deploy:
  provider: pages
  skip_ cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master
  target_branch: gh-pages